package main

import (
	"fmt"
	"os"
	"os/exec"
	"runtime"
	"syscall"
	"time"

	"github.com/kaeawc/spectra/internal/daemon"
	"github.com/kaeawc/spectra/internal/fsutil"
)

type daemonDeps struct {
	paths      func() (daemon.Paths, error)
	executable func() (string, error)
	home       func() (string, error)
	goos       string
	uid        func() int
	mkdirAll   func(string, os.FileMode) error
	writeFile  func(string, []byte, os.FileMode) error
	remove     func(string) error
	readFile   func(string) ([]byte, error)
	run        func(name string, args ...string) error
	output     func(name string, args ...string) ([]byte, error)
	signal     func(int, os.Signal) error
	sleep      func(time.Duration)
}

func defaultDaemonDeps() daemonDeps {
	return daemonDeps{
		paths:      func() (daemon.Paths, error) { return daemon.DefaultPaths(os.Getenv, os.UserHomeDir, runtime.GOOS) },
		executable: os.Executable, home: os.UserHomeDir, goos: runtime.GOOS, uid: os.Getuid,
		mkdirAll: os.MkdirAll, writeFile: fsutil.WriteFileAtomic, remove: os.Remove, readFile: os.ReadFile,
		run: func(name string, args ...string) error {
			// #nosec G204 -- service name and arguments are generated by the installer.
			cmd := exec.Command(name, args...)
			cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
			return cmd.Run()
		},
		output: func(name string, args ...string) ([]byte, error) {
			// #nosec G204 -- service name and arguments are generated by the installer.
			return exec.Command(name, args...).CombinedOutput()
		},
		signal: func(pid int, sig os.Signal) error {
			p, err := os.FindProcess(pid)
			if err != nil {
				return fmt.Errorf("find process: %w", err)
			}
			return p.Signal(sig)
		},
		sleep: time.Sleep,
	}
}

var daemonTermSignal os.Signal = syscall.SIGTERM
