package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/kaeawc/spectra/internal/fsutil"
)

// systemdDaemonUnit is the systemd --user unit file name for the daemon.
const systemdDaemonUnit = "spectra-daemon.service"

// runInstallDaemonLinux dispatches the install-daemon subcommands to their
// systemd --user implementations on Linux.
func runInstallDaemonLinux(args []string) int {
	if len(args) > 0 {
		switch args[0] {
		case "uninstall":
			return runUninstallDaemonLinux(args[1:])
		case "status":
			return runDaemonStatusLinux(args[1:])
		case "print-unit", "print-plist":
			return runPrintDaemonUnit(args[1:])
		}
	}
	opts, ok := parseDaemonAgentOptions("spectra install-daemon", args, os.Stderr)
	if !ok {
		return 2
	}
	unitPath, err := installDaemonUnit(opts, defaultSystemdDaemonDeps())
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 1
	}
	fmt.Fprintf(os.Stdout, "spectra daemon systemd unit installed at %s\n", unitPath)
	if opts.NoLoad {
		fmt.Fprintln(os.Stdout, "Load skipped; run without --no-load to enable it with systemctl --user.")
	}
	return 0
}

func runPrintDaemonUnit(args []string) int {
	opts, ok := parseDaemonAgentOptions("spectra install-daemon print-unit", args, os.Stderr)
	if !ok {
		return 2
	}
	exe, err := os.Executable()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 1
	}
	fmt.Fprint(os.Stdout, daemonSystemdUnit(exe, opts.serveArgs()))
	return 0
}

func runUninstallDaemonLinux(args []string) int {
	fs := flag.NewFlagSet("spectra install-daemon uninstall", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	if err := fs.Parse(args); err != nil {
		return 2
	}
	unitPath, err := uninstallDaemonUnit(defaultSystemdDaemonDeps())
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 1
	}
	fmt.Fprintf(os.Stdout, "spectra daemon systemd unit removed from %s\n", unitPath)
	return 0
}

func runDaemonStatusLinux(args []string) int {
	fs := flag.NewFlagSet("spectra install-daemon status", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	if err := fs.Parse(args); err != nil {
		return 2
	}
	out, _ := daemonUnitStatus(defaultSystemdDaemonDeps())
	fmt.Fprint(os.Stdout, string(out))
	return 0
}

// systemdUserUnitDir returns the systemd --user unit directory, honoring
// $XDG_CONFIG_HOME and falling back to ~/.config.
func systemdUserUnitDir(home string) string {
	base := os.Getenv("XDG_CONFIG_HOME")
	if base == "" {
		base = filepath.Join(home, ".config")
	}
	return filepath.Join(base, "systemd", "user")
}

func installDaemonUnit(opts daemonAgentOptions, deps daemonAgentDeps) (string, error) {
	exe, err := deps.executable()
	if err != nil {
		return "", fmt.Errorf("resolve executable: %w", err)
	}
	home, err := deps.homeDir()
	if err != nil {
		return "", fmt.Errorf("resolve home directory: %w", err)
	}
	unitDir := systemdUserUnitDir(home)
	if err := deps.mkdirAll(unitDir, 0o755); err != nil {
		return "", fmt.Errorf("create systemd user unit directory: %w", err)
	}
	unitPath := filepath.Join(unitDir, systemdDaemonUnit)
	if err := deps.writeFile(unitPath, []byte(daemonSystemdUnit(exe, opts.serveArgs())), 0o644); err != nil {
		return "", fmt.Errorf("write systemd unit: %w", err)
	}
	if opts.NoLoad {
		return unitPath, nil
	}
	if err := deps.run("daemon-reload"); err != nil {
		return "", fmt.Errorf("systemctl --user daemon-reload: %w", err)
	}
	if err := deps.run("enable", "--now", systemdDaemonUnit); err != nil {
		return "", fmt.Errorf("systemctl --user enable --now: %w", err)
	}
	return unitPath, nil
}

func uninstallDaemonUnit(deps daemonAgentDeps) (string, error) {
	home, err := deps.homeDir()
	if err != nil {
		return "", fmt.Errorf("resolve home directory: %w", err)
	}
	unitPath := filepath.Join(systemdUserUnitDir(home), systemdDaemonUnit)
	_ = deps.run("disable", "--now", systemdDaemonUnit)
	if err := deps.remove(unitPath); err != nil && !os.IsNotExist(err) {
		return "", fmt.Errorf("remove systemd unit: %w", err)
	}
	_ = deps.run("daemon-reload")
	return unitPath, nil
}

func daemonUnitStatus(deps daemonAgentDeps) ([]byte, error) {
	// `systemctl --user status` exits non-zero when the unit is inactive;
	// the output is still the useful part, so the error is intentionally
	// ignored by callers.
	return deps.output("status", systemdDaemonUnit, "--no-pager")
}

func defaultSystemdDaemonDeps() daemonAgentDeps {
	return daemonAgentDeps{
		executable: os.Executable,
		homeDir:    os.UserHomeDir,
		mkdirAll:   os.MkdirAll,
		writeFile:  fsutil.WriteFileAtomic,
		remove:     os.Remove,
		run:        runSystemctlUser,
		output:     outputSystemctlUser,
	}
}

func runSystemctlUser(args ...string) error {
	// #nosec G204 -- command is fixed to systemctl --user; args are generated by this installer, no shell.
	cmd := exec.Command("systemctl", append([]string{"--user"}, args...)...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	return cmd.Run()
}

func outputSystemctlUser(args ...string) ([]byte, error) {
	// #nosec G204 -- command is fixed to systemctl --user; args are generated by this installer, no shell.
	return exec.Command("systemctl", append([]string{"--user"}, args...)...).CombinedOutput()
}

// daemonSystemdUnit renders the systemd --user service unit. The daemon logs
// to journald by default; its own --log-file flag (in serveArgs) still
// controls the structured JSONL log.
func daemonSystemdUnit(executable string, serveArgs []string) string {
	var b bytes.Buffer
	b.WriteString("[Unit]\n")
	b.WriteString("Description=Spectra daemon\n")
	b.WriteString("After=network-online.target\n")
	b.WriteString("Wants=network-online.target\n\n")
	b.WriteString("[Service]\n")
	b.WriteString("Type=simple\n")
	fmt.Fprintf(&b, "ExecStart=%s\n", strings.Join(append([]string{executable}, serveArgs...), " "))
	b.WriteString("Restart=on-failure\n")
	b.WriteString("RestartSec=2\n\n")
	b.WriteString("[Install]\n")
	b.WriteString("WantedBy=default.target\n")
	return b.String()
}
