package main

import (
	"bytes"
	"encoding/xml"
	"os"
	"os/exec"
	"strconv"

	"github.com/kaeawc/spectra/internal/fsutil"
)

type scheduleAgentDeps struct {
	executable func() (string, error)
	homeDir    func() (string, error)
	uid        func() string
	mkdirAll   func(string, os.FileMode) error
	writeFile  func(string, []byte, os.FileMode) error
	remove     func(string) error
	run        func(args ...string) error
	output     func(args ...string) ([]byte, error)
}

type scheduleAgentPathSet struct {
	launchAgentsDir string
	logDir          string
	plistPath       string
	stdoutPath      string
	stderrPath      string
}

func defaultScheduleAgentDeps() scheduleAgentDeps {
	return scheduleAgentDeps{
		executable: os.Executable,
		homeDir:    os.UserHomeDir,
		uid: func() string {
			return strconv.Itoa(os.Getuid())
		},
		mkdirAll:  os.MkdirAll,
		writeFile: fsutil.WriteFileAtomic,
		remove:    os.Remove,
		run:       runLaunchctl,
		output:    outputLaunchctl,
	}
}

func runLaunchctl(args ...string) error {
	// #nosec G204 -- command is fixed to launchctl; args are generated by this installer, no shell.
	cmd := exec.Command("launchctl", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	return cmd.Run()
}

func outputLaunchctl(args ...string) ([]byte, error) {
	// #nosec G204 -- command is fixed to launchctl; args are generated by this installer, no shell.
	return exec.Command("launchctl", args...).CombinedOutput()
}

func writePlistKeyString(b *bytes.Buffer, key, value string) {
	b.WriteString("    <key>")
	_ = xml.EscapeText(b, []byte(key))
	b.WriteString("</key>\n")
	writePlistString(b, value)
}

func writePlistString(b *bytes.Buffer, value string) {
	b.WriteString("        <string>")
	_ = xml.EscapeText(b, []byte(value))
	b.WriteString("</string>\n")
}
